# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18y1GEtipJgPmeVNLiSl6irfps0-_y9SG
"""

!pip install streamlit
!pip install pyngrok

import streamlit as st
import joblib
import re
import numpy as np
from scipy.sparse import hstack

# -----------------------------
# Load saved models & vectorizer
# -----------------------------
tfidf = joblib.load(r"C:\Users\User\Downloads\AutoJudge\tfidf_vectorizer.pkl")
clf = joblib.load(r"C:\Users\User\Downloads\AutoJudge\difficulty_score_classifie.pkl")
reg = joblib.load(r"C:\Users\User\Downloads\AutoJudge\difficulty_score_regressor.pkl")

# -----------------------------
# Text cleaning function
# -----------------------------
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s+\-*/=<>]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

# -----------------------------
# Feature engineering functions
# -----------------------------
keywords = [
    'dp', 'dynamic programming', 'graph', 'tree',
    'dfs', 'bfs', 'shortest path',
    'segment tree', 'fenwick',
    'greedy', 'binary search',
    'recursion', 'backtracking'
]

def keyword_count(text):
    return sum(text.count(k) for k in keywords)

def math_symbol_count(text):
    return len(re.findall(r'[+\-*/=<>]', text))

# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(page_title="AutoJudge", layout="centered")

st.title("AutoJudge")
st.subheader("Predict Programming Problem Difficulty")

st.markdown("Paste the problem details below:")

problem_desc = st.text_area("Problem Description", height=200)
input_desc = st.text_area("Input Description", height=150)
output_desc = st.text_area("Output Description", height=150)

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict Difficulty"):
    if problem_desc.strip() == "":
        st.warning("Please enter the problem description.")
    else:
        # Combine text
        combined_text = problem_desc + " " + input_desc + " " + output_desc
        cleaned = clean_text(combined_text)

        # TF-IDF features
        X_tfidf = tfidf.transform([cleaned])

        # Extra features
        text_len = len(cleaned)
        math_cnt = math_symbol_count(cleaned)
        key_cnt = keyword_count(cleaned)

        extra_features = np.array([[text_len, math_cnt, key_cnt]])

        # Final feature vector
        X_final = hstack([X_tfidf, extra_features])

        # Predictions
        pred_class = clf.predict(X_final)[0]
        pred_score = reg.predict(X_final)[0]

        # Output
        st.success("Prediction Successful ][]")
        st.markdown(f"###  Predicted Difficulty Class: **{pred_class}**")
        st.markdown(f"###  Predicted Difficulty Score: **{pred_score:.2f}**")



